#!/usr/bin/env python3
"""Generate the complete in-scope function inventory for the 2026 independent audit.

Parses the Solidity sources directly (not the ABI) so that MODIFIERS — i.e. the real
access control — are captured alongside visibility and mutability. Emits a LaTeX
longtable body to audit/zz_inventory.tex.
"""
import os, re, subprocess, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
EXCLUDE_DIRS = ("lib/", "out/", "cache/", "vendor/", "test/", "broadcast/", "deployments/")

FUNC = re.compile(
    r'\bfunction\s+([A-Za-z_]\w*)\s*\(([^;{]*?)\)\s*((?:[A-Za-z_]\w*(?:\([^()]*\))?\s*)*?)'
    r'(?:returns\s*\(([^;{]*?)\))?\s*[{;]',
    re.S)
CONTRACT = re.compile(r'^\s*(abstract\s+contract|contract|library|interface)\s+([A-Za-z_]\w*)', re.M)

VIS = {"public", "external", "internal", "private"}
MUT = {"view", "pure", "payable"}


def latex(s):
    for a, b in [("\\", "\\textbackslash{}"), ("_", r"\_"), ("&", r"\&"), ("%", r"\%"),
                 ("$", r"\$"), ("#", r"\#"), ("{", r"\{"), ("}", r"\}"), ("~", r"\textasciitilde{}"),
                 ("^", r"\textasciicircum{}")]:
        s = s.replace(a, b)
    return s


def in_scope(path):
    rel = os.path.relpath(path, ROOT)
    if not rel.endswith(".sol"):
        return False
    return not any(rel.startswith(d) for d in EXCLUDE_DIRS)


def owner_of(src, pos):
    """Innermost contract/library/interface declared before `pos`."""
    best = ("", -1)
    for m in CONTRACT.finditer(src):
        if m.start() < pos and m.start() > best[1]:
            best = (m.group(2), m.start())
    return best[0]


def main():
    files = []
    for dirpath, dirnames, filenames in os.walk(ROOT):
        dirnames[:] = [d for d in dirnames
                       if d not in ("lib", "out", "cache", "vendor", "test", "broadcast", "deployments", "audit")]
        for fn in sorted(filenames):
            p = os.path.join(dirpath, fn)
            if in_scope(p):
                files.append(p)
    files.sort(key=lambda p: os.path.relpath(p, ROOT))

    rows, stats = [], {}
    total = 0
    for p in files:
        rel = os.path.relpath(p, ROOT)
        src = open(p).read()
        for m in FUNC.finditer(src):
            name, args, mods = m.group(1), m.group(2), (m.group(3) or "")
            toks = re.findall(r'[A-Za-z_]\w*(?:\([^()]*\))?', mods)
            vis = next((t for t in toks if t in VIS), "internal")
            mut = " ".join(t for t in toks if t in MUT) or "nonpayable"
            gates = [t for t in toks if t not in VIS and t not in MUT
                     and t not in ("override", "virtual", "returns", "memory", "calldata", "storage")]
            owner = owner_of(src, m.start())
            nargs = 0 if not args.strip() else len([a for a in args.split(",") if a.strip()])
            total += 1
            stats.setdefault(owner, {"ext": 0, "int": 0})
            stats[owner]["ext" if vis in ("public", "external") else "int"] += 1
            if vis in ("public", "external"):
                rows.append((owner, name, nargs, vis, mut, ", ".join(gates) or "--", rel))

    out = []
    out.append("% AUTO-GENERATED by audit/zz_gen_inventory.py -- do not edit by hand.\n")
    out.append("\\begin{longtable}{@{}p{3.0cm}p{4.3cm}p{0.5cm}p{1.5cm}p{1.6cm}p{3.4cm}@{}}\n")
    out.append("\\caption{Complete inventory of externally reachable functions in scope.}"
               "\\label{tab:inventory}\\\\\n")
    out.append("\\toprule \\textbf{Contract} & \\textbf{Function} & \\textbf{\\#} & \\textbf{Vis.} & "
               "\\textbf{Mutability} & \\textbf{Access gate} \\\\ \\midrule\n\\endfirsthead\n")
    out.append("\\multicolumn{6}{@{}l}{\\small\\itshape continued from previous page}\\\\\n\\toprule "
               "\\textbf{Contract} & \\textbf{Function} & \\textbf{\\#} & \\textbf{Vis.} & "
               "\\textbf{Mutability} & \\textbf{Access gate} \\\\ \\midrule\n\\endhead\n")
    out.append("\\midrule\\multicolumn{6}{r@{}}{\\small\\itshape continued on next page}\\\\\n\\endfoot\n")
    out.append("\\bottomrule\n\\endlastfoot\n")
    last = None
    for owner, name, nargs, vis, mut, gates, rel in rows:
        shown = latex(owner) if owner != last else ""
        last = owner
        out.append(f"{shown} & \\texttt{{{latex(name)}}} & {nargs} & {vis} & {mut} & "
                   f"\\small {latex(gates)} \\\\\n")
    out.append("\\end{longtable}\n")
    with open(os.path.join(ROOT, "audit", "zz_inventory.tex"), "w") as f:
        f.writelines(out)

    ext = sum(v["ext"] for v in stats.values())
    itn = sum(v["int"] for v in stats.values())
    with open(os.path.join(ROOT, "audit", "zz_inventory_stats.tex"), "w") as f:
        f.write(f"{total} functions across {len(stats)} declared types "
                f"({ext} external/public, {itn} internal/private)")
    print(f"functions={total} external={ext} internal={itn} types={len(stats)} files={len(files)}")


if __name__ == "__main__":
    main()
